#-------------------------------
# General Site Settings

title: vNinjaDFW
description: Sr. PSO Consultant @VMware丨VCIX-DCV丨VCP-NV丨vSAN Specialist丨vExpert**丨vExpert NSX*丨AWS-SAA丨Husband丨Father丨Biker | BBQ | Woodworker | DIYer

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://vninjadfw.github.io/"

#-------------------------------
# About Section
author-name:   Natali Anderson
author-avatar: 09.jpg


#-------------------------------
# Contact links
facebook:  https://www.facebook.com/ryanrpatel
twitter:   https://twitter.com/vNinjaDFW
linkedin:  https://www.linkedin.com/in/ryanpatel/


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: UA-159382822-1 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
remote_theme: artemsheludko/galada
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
