#-------------------------------
# General Site Settings

title: vNinjaDFW | Master Principal Cloud Architect @ Oracle
name: Ryan Patel | Master Principal Cloud Architect @ Oracle
description: Master Principal Cloud Architect @ Oracle丨VCIX-DCV丨VCP-NV丨vExpert PRO
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://vninjadfw.github.io/"

#-------------------------------
# About Section
author-name:  Ryan Patel
author-avatar: about_vninjadfw.jpg


#-------------------------------
# Contact links
twitter:  https://twitter.com/vNinjaDFW/
linkedin: https://www.linkedin.com/in/ryanpatel/
github:   https://github.com/vNinjaDFW


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: https-vninjadfw-github-io # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: G-YX60RJZEBF # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: https://github.us19.list-manage.com/subscribe/post?u=577c05b7927cd37c57c02490b&amp;id=b75a6aea5f


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
